version: '3'
services:
  finik:
    build:
      context: .
      dockerfile: Dockerfile
    image: finik_bot
    volumes:
      - ./main.py:/app/main.py
    environment:
      - PYTHONUNBUFFERED=1
    command: [ "python", "main.py" ]